# 购物系统配置文件

# 管理员账户信息
admin:
  username: admin
  password: admin123

# 数据文件路径
data_files:
  users: res/data/users.csv
  items: res/data/items.csv
  shopping_cart: res/data/shopping_cart.csv
  orders: res/data/orders.csv
  promotions: res/data/promotions.csv

# 订单自动化配置
order_settings:
  auto_update: false
  pending_to_shipped_seconds: 10
  shipped_to_delivered_seconds: 20